My Project: RT_ds18b20.c File Reference
RT_ds18b20.c File Reference
: DS18B20 digital thermometer library for STM32 HAL.
#include <RT_ds18b20.h>
Functions
__weak void delayMicro (uint32_t delay)
void _write_Bit (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, GPIO_PinState bit_tx)
Write a bit with onewire communication.
_Bool _read_Bit (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Read a bit with onewire communication.
void _write_Byte (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, uint8_t data_tx)
Write a byte with onewire communication.
uint8_t _read_Byte (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Read a byte with onewire communication.
HAL_StatusTypeDef DS18B20_Reset_CMD (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Send a command to initializes the onewire communication and the connected device(s).
void DS18B20_ReadROM_CMD (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, uint8_t *dirb)
void DS18B20_MatchROM_CMD (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, uint8_t *dirb)
Send a command to select a onewire device.
HAL_StatusTypeDef DS18B20_ConvertT_CMD (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Send a command to convert A/D the temperature of the selected onewire device.
HAL_StatusTypeDef DS18B20_ReadScratchpad_CMD (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, uint8_t *data, uint8_t n_bytes)
Send a command to read bytes of the scratchpad.
void DS18B20_WriteScratchpad_CMD (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, uint8_t th_reg, uint8_t tl_reg, ds18b20_resolution_t resol)
Send a command to write in scratchpad of the selected onewire device.
void DS18B20_SearchROM_CMD (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, uint8_t *dirb)
Send a command to search all ROM codes of onewire bus.
void DS18B20_SkipROM_CMD (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Send a command to select all onewire device.
void DS18B20_CopyScratchpad_CMD (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Send a command to copy TH, TL and configuration register to EEPROM.
void DS18B20_RecallE2_CMD (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Send a command to restore TH, TL and configuration register from EEPROM.
HAL_StatusTypeDef DS18B20_SetResolution (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, uint8_t *dirb, ds18b20_resolution_t resol)
Shortcut to read the temperature of a onewire device.
float DS18B20_Decode_Temperature (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, uint8_t *data)
Read the scratchpad of the selected onewire device and decode the data temperature.
float DS18B20_ConvertRead_Temp (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, uint8_t *dirb)
Shortcut to do the conversion and read of the temperature in a onewire device.
HAL_StatusTypeDef DS18B20_All_Convert (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Shortcut to do the A/D conversion on all onewire device(s).
float DS18B20_Read_Temp (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, uint8_t *dirb)
Shortcut to read the temperature of a onewire device.
Detailed Description
: DS18B20 digital thermometer library for STM32 HAL.
Author
Rubén Torres Bermúdez ruben.nosp@m.torr.nosp@m.esber.nosp@m.mude.nosp@m.z@gma.nosp@m.il.c.nosp@m.om
Attention
Created on: 13.09.2021
Description: This library is used to control one or more DS18B20 digital thermometers with STM32 HAL.
Basic example: DS18B20_Reset_CMD(DS_GPIO_Port, DS_Pin); DS18B20_ReadROM_CMD(DS_GPIO_Port, DS_Pin, dirb); DS18B20_Reset_CMD(DS_GPIO_Port, DS_Pin); DS18B20_SetResolution(DS_GPIO_Port, DS_Pin, dirb, DS18B20_RESOLUTION_10); DS18B20_All_Convert(DS_GPIO_Port, DS_Pin); temp = DS18B20_Read_Temp(DS_GPIO_Port, DS_Pin, dirb);
Warning: Before sending each command (ending in _CMD()), use the DS18B20_Reset_CMD() function. The GPIO used must be OUTPUT OPEN DRAIN and HIGH output speed. Configure the delayMicros() function in your main.c or in RT_ds18b20.c
Copyright (C) 2021 Rubén Torres Bermúdez
Definition in file RT_ds18b20.c.
Function Documentation
_read_Bit()
_Bool _read_Bit (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Read a bit with onewire communication.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
Return values
The bit read.
Definition at line 75 of file RT_ds18b20.c.
References delayMicro().
Referenced by _read_Byte().
_read_Byte()
uint8_t _read_Byte (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Read a byte with onewire communication.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
Return values
The byte read.
Definition at line 119 of file RT_ds18b20.c.
References _read_Bit().
Referenced by DS18B20_ReadROM_CMD(), and DS18B20_ReadScratchpad_CMD().
_write_Bit()
void _write_Bit (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, GPIO_PinState bit_tx)
Write a bit with onewire communication.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
bit_tx specifies the value to be written. This parameter can be one of the GPIO_PinState enum values:
GPIO_PIN_RESET: to write 0.
GPIO_PIN_SET: to write 1.
Return values
None.
Definition at line 57 of file RT_ds18b20.c.
References delayMicro().
Referenced by _write_Byte().
_write_Byte()
void _write_Byte (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, uint8_t data_tx)
Write a byte with onewire communication.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
data_tx specifies the byte to be written.
Return values
None
Definition at line 97 of file RT_ds18b20.c.
References _write_Bit(), and delayMicro().
Referenced by DS18B20_ConvertT_CMD(), DS18B20_CopyScratchpad_CMD(), DS18B20_MatchROM_CMD(), DS18B20_ReadROM_CMD(), DS18B20_ReadScratchpad_CMD(), DS18B20_RecallE2_CMD(), DS18B20_SkipROM_CMD(), and DS18B20_WriteScratchpad_CMD().
delayMicro()
__weak void delayMicro (uint32_t delay)
Definition at line 37 of file RT_ds18b20.c.
Referenced by _read_Bit(), _write_Bit(), _write_Byte(), DS18B20_ConvertT_CMD(), and DS18B20_Reset_CMD().
DS18B20_All_Convert()
HAL_StatusTypeDef DS18B20_All_Convert (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Shortcut to do the A/D conversion on all onewire device(s).
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
Return values
This parameter can be one of the enum values:
HAL_OK: if success.
HAL_ERROR: if not success.
Definition at line 421 of file RT_ds18b20.c.
References DS18B20_ConvertT_CMD(), DS18B20_Reset_CMD(), and DS18B20_SkipROM_CMD().
Referenced by aocs_get_temp().
DS18B20_ConvertRead_Temp()
float DS18B20_ConvertRead_Temp (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, uint8_t * dirb)
Shortcut to do the conversion and read of the temperature in a onewire device.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
dirb specifies the 64-bit lasered ROM code of the onewire device LSBF.
Return values
A float value that specifies the temperature of the onewire device or -99 if there was a error.
Definition at line 394 of file RT_ds18b20.c.
References DS18B20_ConvertT_CMD(), DS18B20_Decode_Temperature(), DS18B20_MatchROM_CMD(), DS18B20_ReadScratchpad_CMD(), and DS18B20_Reset_CMD().
DS18B20_ConvertT_CMD()
HAL_StatusTypeDef DS18B20_ConvertT_CMD (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Send a command to convert A/D the temperature of the selected onewire device.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
Return values
This parameter can be one of the enum values:
HAL_OK: if ADC could be done.
HAL_ERROR: if ADC could not be performed.
Definition at line 206 of file RT_ds18b20.c.
References _write_Byte(), and delayMicro().
Referenced by DS18B20_All_Convert(), and DS18B20_ConvertRead_Temp().
DS18B20_CopyScratchpad_CMD()
void DS18B20_CopyScratchpad_CMD (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Send a command to copy TH, TL and configuration register to EEPROM.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
Return values
None.
Definition at line 302 of file RT_ds18b20.c.
References _write_Byte().
DS18B20_Decode_Temperature()
float DS18B20_Decode_Temperature (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, uint8_t * data)
Read the scratchpad of the selected onewire device and decode the data temperature.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15)
data specifies two bytes with DS18B20 temperature.
Return values
A float value that specifies the decoded temperature.
Definition at line 364 of file RT_ds18b20.c.
Referenced by DS18B20_ConvertRead_Temp(), and DS18B20_Read_Temp().
DS18B20_MatchROM_CMD()
void DS18B20_MatchROM_CMD (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, uint8_t * dirb)
Send a command to select a onewire device.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
dirb specifies the 64-bit lasered ROM code of the onewire device LSBF.
Return values
None.
Definition at line 183 of file RT_ds18b20.c.
References _write_Byte().
Referenced by DS18B20_ConvertRead_Temp(), DS18B20_Read_Temp(), and DS18B20_SetResolution().
DS18B20_Read_Temp()
float DS18B20_Read_Temp (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, uint8_t * dirb)
Shortcut to read the temperature of a onewire device.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
dirb specifies the 64-bit lasered ROM code of the onewire device LSBF.
Return values
A float value that specifies the temperature of the onewire device or -99.0 if there was a error.
Definition at line 440 of file RT_ds18b20.c.
References DS18B20_Decode_Temperature(), DS18B20_MatchROM_CMD(), DS18B20_ReadScratchpad_CMD(), and DS18B20_Reset_CMD().
Referenced by aocs_get_temp().
DS18B20_ReadROM_CMD()
void DS18B20_ReadROM_CMD (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, uint8_t * dirb)
Definition at line 159 of file RT_ds18b20.c.
References _read_Byte(), and _write_Byte().
DS18B20_ReadScratchpad_CMD()
HAL_StatusTypeDef DS18B20_ReadScratchpad_CMD (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, uint8_t * data, uint8_t n_bytes)
Send a command to read bytes of the scratchpad.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
data buffer where the read bytes will be stored.
n_bytes specifies the numbers of bit to be read.
Return values
This parameter can be one of the enum values:
HAL_OK: if success.
HAL_ERROR: if not success.
Definition at line 233 of file RT_ds18b20.c.
References _read_Byte(), and _write_Byte().
Referenced by DS18B20_ConvertRead_Temp(), DS18B20_Read_Temp(), and DS18B20_SetResolution().
DS18B20_RecallE2_CMD()
void DS18B20_RecallE2_CMD (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Send a command to restore TH, TL and configuration register from EEPROM.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
Return values
None.
Definition at line 315 of file RT_ds18b20.c.
References _write_Byte().
DS18B20_Reset_CMD()
HAL_StatusTypeDef DS18B20_Reset_CMD (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Send a command to initializes the onewire communication and the connected device(s).
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
Return values
This parameter can be one of the enum values:
HAL_OK: if there are device(s) on the onewire communication.
HAL_ERROR: if there aren't device(s) on the onewire communication.
Definition at line 145 of file RT_ds18b20.c.
References delayMicro().
Referenced by aocs_config_temp(), aocs_get_temp(), DS18B20_All_Convert(), DS18B20_ConvertRead_Temp(), DS18B20_Read_Temp(), and DS18B20_SetResolution().
DS18B20_SearchROM_CMD()
void DS18B20_SearchROM_CMD (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, uint8_t * dirb)
Send a command to search all ROM codes of onewire bus.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
dirb Pointer to a direction of DS18B20
Return values
None.
Definition at line 275 of file RT_ds18b20.c.
DS18B20_SetResolution()
HAL_StatusTypeDef DS18B20_SetResolution (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, uint8_t * dirb, ds18b20_resolution_t resol)
Shortcut to read the temperature of a onewire device.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
dirb Pointer to a direction of DS18B20
resol Resolution to be set
Return values
This parameter can be one of the enum values:
HAL_OK: if success.
HAL_ERROR: if not success.
Definition at line 339 of file RT_ds18b20.c.
References DS18B20_MatchROM_CMD(), DS18B20_ReadScratchpad_CMD(), DS18B20_Reset_CMD(), and DS18B20_WriteScratchpad_CMD().
Referenced by aocs_config_temp().
DS18B20_SkipROM_CMD()
void DS18B20_SkipROM_CMD (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Send a command to select all onewire device.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
Return values
None.
Definition at line 289 of file RT_ds18b20.c.
References _write_Byte().
Referenced by DS18B20_All_Convert().
DS18B20_WriteScratchpad_CMD()
void DS18B20_WriteScratchpad_CMD (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, uint8_t th_reg, uint8_t tl_reg, ds18b20_resolution_t resol)
Send a command to write in scratchpad of the selected onewire device.
Parameters
GPIOx where x can be (A..K) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_PIN_x where x can be (0..15).
th_reg specifies the value to be written in the TH register.
tl_reg specifies the value to be written in the TL register.
resol specifies the resolution of the ADC onewire device.
Return values
None.
Definition at line 257 of file RT_ds18b20.c.
References _write_Byte().
Referenced by DS18B20_SetResolution().