My Project: aocs.c File Reference
aocs.c File Reference
: AOCS for FyCUS 2023.
#include "aocs.h"
Functions
HAL_StatusTypeDef aocs_config_gnss ()
HAL_StatusTypeDef aocs_config_magnetometer ()
HAL_StatusTypeDef aocs_config_imu ()
HAL_StatusTypeDef aocs_config_altimeter ()
HAL_StatusTypeDef aocs_config_temp ()
HAL_StatusTypeDef aocs_get_gnss ()
HAL_StatusTypeDef aocs_get_mag ()
HAL_StatusTypeDef aocs_get_imu ()
HAL_StatusTypeDef aocs_get_accel ()
HAL_StatusTypeDef aocs_get_gyro ()
HAL_StatusTypeDef aocs_get_altimeter ()
HAL_StatusTypeDef aocs_get_temp ()
HAL_StatusTypeDef aocs_get_pubx ()
Variables
imu_t imu = {0}
magneto_t mag = {0}
altimeter_t altimeter = {0}
temperatures_t temps = {0}
uint8_t gnss_ring [GNSS_RING_BUFFER_SIZE] = {0}
volatile uint32_t gnss_ring_pos = 0
volatile uint32_t gnss_ring_last_end = 0
volatile uint32_t gnss_ring_last_ini = 0
uint8_t pubx_ring [200] = {0}
gnss_nmea_rmc_sentence_t rmc
gnss_nmea_gga_sentence_t gga
gnss_nmea_t gnss = {&rmc, &gga}
Detailed Description
: AOCS for FyCUS 2023.
Author
Rubén Torres Bermúdez ruben.nosp@m.torr.nosp@m.esber.nosp@m.mude.nosp@m.z@gma.nosp@m.il.c.nosp@m.om
Attention
Created on: 05.09.2023
Description: This library is used to control the AOCS subsystem in FyCUS 2023 project
Copyright (C) 2023 Rubén Torres Bermúdez
Definition in file aocs.c.
Function Documentation
aocs_config_altimeter()
HAL_StatusTypeDef aocs_config_altimeter () inline
Configure MS5607 altimeter
Returns
HAL status
Definition at line 146 of file aocs.c.
References altimeter, ms5607_readCalibration(), and ms5607_reset().
Referenced by check_status().
aocs_config_gnss()
HAL_StatusTypeDef aocs_config_gnss () inline
Configure NEO GNSS receiver
Returns
HAL status
Definition at line 64 of file aocs.c.
aocs_config_imu()
HAL_StatusTypeDef aocs_config_imu () inline
Configure LSM6DSO IMU
Returns
HAL status
Definition at line 130 of file aocs.c.
References hi2c1, lsm6dso_config(), and lsm6dso_whoIam().
Referenced by check_status().
aocs_config_magnetometer()
HAL_StatusTypeDef aocs_config_magnetometer () inline
Configure LIS2MDL magnetometer
Returns
HAL status
Definition at line 112 of file aocs.c.
References hi2c1, lis2mdl_config(), and lis2mdl_whoIam().
Referenced by check_status().
aocs_config_temp()
HAL_StatusTypeDef aocs_config_temp () inline
Configure DS18B20 temperature sensors
Returns
HAL status
Definition at line 163 of file aocs.c.
References DS18B20_Reset_CMD(), DS18B20_SetResolution(), and temps.
Referenced by check_status().
aocs_get_accel()
HAL_StatusTypeDef aocs_get_accel () inline
Get linear acceleration from LSM6DSO
Returns
HAL status
Definition at line 253 of file aocs.c.
References hi2c1, imu, lsm6dso_readAccel(), and lsm6dso_readStatus().
aocs_get_altimeter()
HAL_StatusTypeDef aocs_get_altimeter () inline
Get altitude, pressure and temperature from MS5607
Returns
HAL status
Definition at line 286 of file aocs.c.
References altimeter, ms5607_getAltitude(), and ms5607_getTempPressure().
aocs_get_gnss()
HAL_StatusTypeDef aocs_get_gnss () inline
Decode NMEA message into from ring buffer data
Returns
HAL status
Definition at line 198 of file aocs.c.
References gnss, gnss_nmea_GetData(), gnss_ring, gnss_ring_last_end, and gnss_ring_last_ini.
aocs_get_gyro()
HAL_StatusTypeDef aocs_get_gyro () inline
Get angular acceleration from LSM6DSO
Returns
HAL status
Definition at line 270 of file aocs.c.
References hi2c1, imu, lsm6dso_readGyro(), and lsm6dso_readStatus().
aocs_get_imu()
HAL_StatusTypeDef aocs_get_imu () inline
Get angular and linear acceleration from LSM6DSO
Returns
HAL status
Definition at line 227 of file aocs.c.
References hi2c1, imu, lsm6dso_readAccel(), lsm6dso_readGyro(), lsm6dso_readStatus(), and lsm6dso_readTemp().
aocs_get_mag()
HAL_StatusTypeDef aocs_get_mag () inline
Get megnetometer values from LIS2MDL
Returns
HAL status
Definition at line 208 of file aocs.c.
References hi2c1, lis2mdl_readMag(), lis2mdl_readTemp(), lis2mdl_status(), and mag.
aocs_get_pubx()
HAL_StatusTypeDef aocs_get_pubx () inline
Get PUBX message from NEO GNSS receiver
Returns
HAL status
Definition at line 321 of file aocs.c.
References pubx_ring.
aocs_get_temp()
HAL_StatusTypeDef aocs_get_temp () inline
Get temperature from DS18B20
Returns
HAL status
Definition at line 298 of file aocs.c.
References DS18B20_All_Convert(), DS18B20_Read_Temp(), DS18B20_Reset_CMD(), and temps.
Variable Documentation
altimeter
altimeter_t altimeter = {0}
Definition at line 32 of file aocs.c.
Referenced by aocs_config_altimeter(), and aocs_get_altimeter().
gga
gnss_nmea_gga_sentence_t gga
Definition at line 44 of file aocs.c.
gnss
gnss_nmea_t gnss = {&rmc, &gga}
Definition at line 45 of file aocs.c.
Referenced by aocs_get_gnss().
gnss_ring
uint8_t gnss_ring[GNSS_RING_BUFFER_SIZE] = {0}
Definition at line 38 of file aocs.c.
Referenced by aocs_get_gnss().
gnss_ring_last_end
volatile uint32_t gnss_ring_last_end = 0
Definition at line 40 of file aocs.c.
Referenced by aocs_get_gnss().
gnss_ring_last_ini
volatile uint32_t gnss_ring_last_ini = 0
Definition at line 41 of file aocs.c.
Referenced by aocs_get_gnss().
gnss_ring_pos
volatile uint32_t gnss_ring_pos = 0
Definition at line 39 of file aocs.c.
imu
imu_t imu = {0}
Definition at line 26 of file aocs.c.
Referenced by aocs_get_accel(), aocs_get_gyro(), and aocs_get_imu().
mag
magneto_t mag = {0}
Definition at line 29 of file aocs.c.
Referenced by aocs_get_mag().
pubx_ring
uint8_t pubx_ring[200] = {0}
Definition at line 42 of file aocs.c.
Referenced by aocs_get_pubx().
rmc
gnss_nmea_rmc_sentence_t rmc
Definition at line 43 of file aocs.c.
temps
temperatures_t temps = {0}
Definition at line 35 of file aocs.c.
Referenced by aocs_config_temp(), and aocs_get_temp().