My Project: bus_packet.c File Reference
bus_packet.c File Reference
: Encoder and decoder for bus packet FyCUS 2023
#include "bus_packet.h"
Functions
HAL_StatusTypeDef bus_packet_Decode (uint8_t *buffer, bus_packet_t *packet)
HAL_StatusTypeDef bus_packet_Encode (uint8_t type, uint8_t apid, uint8_t ecf_flag, uint8_t *data, uint32_t data_length, bus_packet_t *packet)
void bus_packet_Packetize (uint8_t *buffer, bus_packet_t *packet)
HAL_StatusTypeDef bus_packet_EncodePacketize (uint8_t type, uint8_t apid, uint8_t ecf_flag, uint8_t *data, uint32_t data_length, uint8_t *buffer_out)
bus_sync_flag_t bus_packet_SyncFrameDetect (bus_sync_flag_t flag, uint8_t received_data)
uint16_t bus_packet_CRC16CCSDSCalculate (int16_t seed, uint8_t *buf, uint32_t len)
Variables
const uint8_t BUS_PACKET_FRAME_SYNC [4] = {0x1A, 0xCF, 0xFC, 0x1D}
Detailed Description
: Encoder and decoder for bus packet FyCUS 2023
Author
Rubén Torres Bermúdez ruben.nosp@m.torr.nosp@m.esber.nosp@m.mude.nosp@m.z@gma.nosp@m.il.c.nosp@m.om
Attention
Created on: 11.08.2023
Description: This library is used to encode, packetize, decode and sync data to communicate different systems connected to the internal bus of FyCUS 2023 prototype.
Example: bus_packet_t packet = {0}; uint8_t data[BUS_PACKET_DATA_SIZE] = {100,1,12,234,34,3}; buffer_in[BUS_PACKET_BUS_SIZE] = {0}; bus_packet_EncodePacketize(1, 90, 1, data, 6, buffer_in); if (bus_packet_Decode(buffer_in, &packet) != HAL_OK) Error_Handle(); // Approximated time for max buffer: 8330 clock cycles
Warning: With STM32, define your own CRC handle and make sure that is correctly configured: bus_packet_CRC16CCSDSConfig();
Poly 16 bits: X^16 + X^12 + X^5 + 1
8 bits input
Input and output without bit inversion
Copyright (C) 2023 Rubén Torres Bermúdez
Definition in file bus_packet.c.
Function Documentation
bus_packet_CRC16CCSDSCalculate()
uint16_t bus_packet_CRC16CCSDSCalculate (int16_t seed, uint8_t * buf, uint32_t len)
Definition at line 334 of file bus_packet.c.
Referenced by bus_packet_Decode(), bus_packet_Encode(), bus_packet_EncodePacketize(), tf_packet_Decode(), and tf_packet_Packetize().
bus_packet_Decode()
HAL_StatusTypeDef bus_packet_Decode (uint8_t * buffer, bus_packet_t * packet)
Decode data buffer that contain a bus packet
Parameters
buffer Data buffer with a bus packet to decode
packet Pointer to bus packet structure to save data
Returns
HAL status
Definition at line 54 of file bus_packet.c.
References bus_packet_CRC16CCSDSCalculate(), and hcrc.
bus_packet_Encode()
HAL_StatusTypeDef bus_packet_Encode (uint8_t type, uint8_t apid, uint8_t ecf_flag, uint8_t * data, uint32_t data_length, bus_packet_t * packet)
Encode data into a bus packet structure
Parameters
type
BUS_PACKET_TYPE_TM if a TM data is contained
BUS_PACKET_TYPE_TC if a TM data is contained
apid APID number for contained data
ecf_flag
BUS_PACKET_ECF_NOT_EXIST if an Error Control Field will be not encoded
BUS_PACKET_ECF_EXIST if an Error Control Field will be encoded
data Pointer to data that will be encoded
data_length Data length
packet Pointer to bus packet structure to save data
Returns
HAL status
Definition at line 104 of file bus_packet.c.
References bus_packet_CRC16CCSDSCalculate(), and hcrc.
bus_packet_EncodePacketize()
HAL_StatusTypeDef bus_packet_EncodePacketize (uint8_t type, uint8_t apid, uint8_t ecf_flag, uint8_t * data, uint32_t data_length, uint8_t * buffer_out)
Encode and packetize data into a buffer for to be transmitted
Parameters
type
BUS_PACKET_TYPE_TM if a TM data is contained
BUS_PACKET_TYPE_TC if a TM data is contained
apid APID number for contained data
ecf_flag
BUS_PACKET_ECF_NOT_EXIST if an Error Control Field will be not encoded
BUS_PACKET_ECF_EXIST if an Error Control Field will be encoded
data Pointer to data that will be encoded
data_length Data length
buffer_out Pointer to a data buffer for to be transmitted
Returns
HAL status
Definition at line 178 of file bus_packet.c.
References bus_packet_CRC16CCSDSCalculate(), and hcrc.
Referenced by intelliOBC_TC(), send_ack(), send_data_saving(), send_nack(), and send_programmed_TM().
bus_packet_Packetize()
void bus_packet_Packetize (uint8_t * buffer, bus_packet_t * packet)
Packetize an encoded space packet to be transmitted
Parameters
buffer Pointer to a data buffer for to be transmitted
packet Pointer to a space packet to be packetized
Definition at line 144 of file bus_packet.c.
bus_packet_SyncFrameDetect()
bus_sync_flag_t bus_packet_SyncFrameDetect (bus_sync_flag_t flag, uint8_t received_data)
Detect next flag sync based on the input flag and input data
Parameters
flag Last flag of your Sync frame
received_data Current data received
Returns
Current flag of your Sync frame
Definition at line 211 of file bus_packet.c.
References BUS_PACKET_FRAME_SYNC.
Variable Documentation
BUS_PACKET_FRAME_SYNC
const uint8_t BUS_PACKET_FRAME_SYNC[4] = {0x1A, 0xCF, 0xFC, 0x1D}
Definition at line 45 of file bus_packet.c.
Referenced by bus_packet_SyncFrameDetect(), send_ack(), send_nack(), and send_TM().