My Project: intelli.c File Reference
intelli.c File Reference
: OBC Intelligence for FyCUS 2023.
#include "intelli.h"
Functions
HAL_StatusTypeDef set_time (uint8_t hours, uint8_t min, uint8_t sec)
HAL_StatusTypeDef get_time (uint8_t *hours, uint8_t *min, uint8_t *sec)
uint8_t dataRequired2bytes (tc_required_data_t requirements, uint8_t *pdata)
void check_status ()
HAL_StatusTypeDef send_TM ()
HAL_StatusTypeDef send_programmed_TM ()
HAL_StatusTypeDef send_data_saving ()
HAL_StatusTypeDef send_ack (UART_HandleTypeDef *huart)
HAL_StatusTypeDef send_nack (UART_HandleTypeDef *huart)
void intelliOBC_TC (apid_t apid, uint8_t *data)
void intelliOBC_TM (uint8_t apid, uint8_t *data)
Variables
uint8_t modem_buffer_tx [BUS_PACKET_BUS_SIZE+BUS_PACKET_FRAME_SYNC_SIZE] = {0}
uint8_t *const modem_data_tx = &modem_buffer_tx[BUS_PACKET_FRAME_SYNC_SIZE]
uint8_t eps_buffer_tx [BUS_PACKET_BUS_SIZE+BUS_PACKET_FRAME_SYNC_SIZE] = {0}
uint8_t *const eps_data_tx = &eps_buffer_tx[BUS_PACKET_FRAME_SYNC_SIZE]
uint8_t buffer_data [BUS_PACKET_DATA_SIZE]
uint32_t last_tc_apid = 0
uint32_t last_tc_number = 0
uint32_t last_tm_apid = 0
uint32_t last_tm_number = 0
tc_required_data_t programmed_tm
sc_status_t sc_status
eps_data_t eps
RTC_TimeTypeDef rtc
Detailed Description
: OBC Intelligence for FyCUS 2023.
Author
Rubén Torres Bermúdez ruben.nosp@m.torr.nosp@m.esber.nosp@m.mude.nosp@m.z@gma.nosp@m.il.c.nosp@m.om
Attention
Created on: 10.09.2023
Description: This library is used to control the OBC intelligence in FyCUS 2023 project
Copyright (C) 2023 Rubén Torres Bermúdez
Definition in file intelli.c.
Function Documentation
check_status()
void check_status ()
Check status of different subsystems and components
Definition at line 227 of file intelli.c.
References aocs_config_altimeter(), aocs_config_imu(), aocs_config_magnetometer(), aocs_config_temp(), and sc_status.
dataRequired2bytes()
uint8_t dataRequired2bytes (tc_required_data_t requirements, uint8_t * pdata)
Set a byte array with data required for transmission
Parameters
requirements Data required. See tc_required_data_t
pdata Pointer to byte array
Returns
Length of byte array
Definition at line 135 of file intelli.c.
Referenced by intelliOBC_TC(), send_data_saving(), and send_programmed_TM().
get_time()
HAL_StatusTypeDef get_time (uint8_t * hours, uint8_t * min, uint8_t * sec)
Parameters
hours
min
sec
Returns
Definition at line 120 of file intelli.c.
References rtc.
intelliOBC_TC()
void intelliOBC_TC (apid_t apid, uint8_t * data)
Intelligence for a received telecommand
Parameters
apid Received APID
data Received data
Definition at line 352 of file intelli.c.
References buffer_data, bus_packet_EncodePacketize(), dataRequired2bytes(), modem_data_tx, programmed_tm, sc_status, and send_TM().
intelliOBC_TM()
void intelliOBC_TM (uint8_t apid, uint8_t * data)
Intelligence for a received telemetry
Parameters
apid Received APID
data Received data
Definition at line 464 of file intelli.c.
References eps, and sc_status.
send_ack()
HAL_StatusTypeDef send_ack (UART_HandleTypeDef * huart)
Send ACK
Parameters
huart UART handle to send packet.
Returns
HAL status
Definition at line 313 of file intelli.c.
References bus_packet_EncodePacketize(), and BUS_PACKET_FRAME_SYNC.
send_data_saving()
HAL_StatusTypeDef send_data_saving ()
Send telemetry data to modem for saving data
Returns
HAL status
Definition at line 285 of file intelli.c.
References buffer_data, bus_packet_EncodePacketize(), dataRequired2bytes(), modem_data_tx, and send_TM().
send_nack()
HAL_StatusTypeDef send_nack (UART_HandleTypeDef * huart)
Send NACK
Parameters
huart UART handle to send packet.
Returns
HAL status
Definition at line 330 of file intelli.c.
References bus_packet_EncodePacketize(), and BUS_PACKET_FRAME_SYNC.
send_programmed_TM()
HAL_StatusTypeDef send_programmed_TM ()
Send programmed telemetry data to modem for transmission to ground
Returns
HAL status
Definition at line 257 of file intelli.c.
References buffer_data, bus_packet_EncodePacketize(), dataRequired2bytes(), modem_data_tx, programmed_tm, and send_TM().
send_TM()
HAL_StatusTypeDef send_TM ()
Send telemetry data to modem for transmission to ground
Returns
HAL status
Definition at line 247 of file intelli.c.
References BUS_PACKET_FRAME_SYNC, modem_buffer_tx, and modem_data_tx.
Referenced by intelliOBC_TC(), send_data_saving(), and send_programmed_TM().
set_time()
HAL_StatusTypeDef set_time (uint8_t hours, uint8_t min, uint8_t sec)
Parameters
hours
min
sec
Returns
Definition at line 105 of file intelli.c.
References rtc.
Variable Documentation
buffer_data
uint8_t buffer_data[BUS_PACKET_DATA_SIZE]
Definition at line 30 of file intelli.c.
Referenced by intelliOBC_TC(), send_data_saving(), and send_programmed_TM().
eps
eps_data_t eps
Definition at line 45 of file intelli.c.
Referenced by intelliOBC_TM().
eps_buffer_tx
uint8_t eps_buffer_tx[BUS_PACKET_BUS_SIZE+BUS_PACKET_FRAME_SYNC_SIZE] = {0}
Definition at line 27 of file intelli.c.
eps_data_tx
uint8_t* const eps_data_tx = &eps_buffer_tx[BUS_PACKET_FRAME_SYNC_SIZE]
Definition at line 28 of file intelli.c.
last_tc_apid
uint32_t last_tc_apid = 0
Definition at line 34 of file intelli.c.
last_tc_number
uint32_t last_tc_number = 0
Definition at line 35 of file intelli.c.
last_tm_apid
uint32_t last_tm_apid = 0
Definition at line 36 of file intelli.c.
last_tm_number
uint32_t last_tm_number = 0
Definition at line 37 of file intelli.c.
modem_buffer_tx
uint8_t modem_buffer_tx[BUS_PACKET_BUS_SIZE+BUS_PACKET_FRAME_SYNC_SIZE] = {0}
Definition at line 24 of file intelli.c.
Referenced by send_TM().
modem_data_tx
uint8_t* const modem_data_tx = &modem_buffer_tx[BUS_PACKET_FRAME_SYNC_SIZE]
Definition at line 25 of file intelli.c.
Referenced by intelliOBC_TC(), send_data_saving(), send_programmed_TM(), and send_TM().
programmed_tm
tc_required_data_t programmed_tm
Initial value:
=
        REQUIRED_DATA_GNSS | REQUIRED_DATA_ACELL | REQUIRED_DATA_GYRO | REQUIRED_DATA_TEMPERATURE_OUTDOOR | REQUIRED_DATA_BATTERY_VOLTAGE
Definition at line 38 of file intelli.c.
Referenced by intelliOBC_TC(), and send_programmed_TM().
rtc
RTC_TimeTypeDef rtc
Definition at line 48 of file intelli.c.
Referenced by get_time(), and set_time().
sc_status
sc_status_t sc_status
Definition at line 42 of file intelli.c.
Referenced by check_status(), intelliOBC_TC(), and intelliOBC_TM().