My Project: lis2mdltr.c File Reference
lis2mdltr.c File Reference
: LIS2MDLTR magnetometer library.
#include "lis2mdltr.h"
Functions
HAL_StatusTypeDef lis2mdl_config (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout)
uint8_t lis2mdl_status (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout)
HAL_StatusTypeDef lis2mdl_single_conversion (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout)
HAL_StatusTypeDef lis2mdl_readMag (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout, int16_t *x, int16_t *y, int16_t *z)
HAL_StatusTypeDef lis2mdl_readTemp (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout, float *temp)
uint8_t lis2mdl_whoIam (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout)
uint8_t lis2mdl_resetSoftware (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout)
HAL_StatusTypeDef lis2mdl_rebootMemory (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout)
uint8_t lis2mdl_selfTest (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout)
Detailed Description
: LIS2MDLTR magnetometer library.
Author
Rubén Torres Bermúdez ruben.nosp@m.torr.nosp@m.esber.nosp@m.mude.nosp@m.z@gma.nosp@m.il.c.nosp@m.om
Attention
Created on: 29.04.2023
Description: This library is used to control a LIS2MDLTR magnetometer.
Copyright (C) 2023 Rubén Torres Bermúdez
Definition in file lis2mdltr.c.
Function Documentation
lis2mdl_config()
HAL_StatusTypeDef lis2mdl_config (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout)
Common configuration for LIS2MDL
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
Returns
HAL status
Definition at line 30 of file lis2mdltr.c.
Referenced by aocs_config_magnetometer().
lis2mdl_readMag()
HAL_StatusTypeDef lis2mdl_readMag (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout, int16_t * x, int16_t * y, int16_t * z)
Read magnetometer sensor
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
x Pointer to x-axis value
y Pointer to y-axis value
z Pointer to z-axis value
Returns
HAL status
Definition at line 102 of file lis2mdltr.c.
Referenced by aocs_get_mag().
lis2mdl_readTemp()
HAL_StatusTypeDef lis2mdl_readTemp (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout, float * temp)
Read temperature sensor
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
temp Pointer to temperature
Returns
HAL status
Definition at line 128 of file lis2mdltr.c.
Referenced by aocs_get_mag().
lis2mdl_rebootMemory()
HAL_StatusTypeDef lis2mdl_rebootMemory (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout)
Reboot memory contents
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
Returns
HAL status
Definition at line 178 of file lis2mdltr.c.
lis2mdl_resetSoftware()
uint8_t lis2mdl_resetSoftware (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout)
Software reset
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
Returns
HAL status
Definition at line 163 of file lis2mdltr.c.
Referenced by lis2mdl_selfTest().
lis2mdl_selfTest()
uint8_t lis2mdl_selfTest (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout)
Self-test utility (NO TESTED FUNCTION)
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
Returns
HAL status
Definition at line 200 of file lis2mdltr.c.
References lis2mdl_resetSoftware(), and lis2mdl_status().
lis2mdl_single_conversion()
HAL_StatusTypeDef lis2mdl_single_conversion (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout)
Perform a single conversion
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
Returns
HAL status
Definition at line 81 of file lis2mdltr.c.
lis2mdl_status()
uint8_t lis2mdl_status (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout)
Read status register
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
Returns
HAL status
Definition at line 64 of file lis2mdltr.c.
Referenced by aocs_get_mag(), and lis2mdl_selfTest().
lis2mdl_whoIam()
uint8_t lis2mdl_whoIam (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout)
Read WHO I AM register
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
Returns
Device response
Definition at line 148 of file lis2mdltr.c.
References hi2c1.
Referenced by aocs_config_magnetometer().