My Project: lsm6dso.c File Reference
lsm6dso.c File Reference
: LSM6DSO IMU library.
#include "lsm6dso.h"
Macros
#define INC_LSM6DSO_C_
Functions
HAL_StatusTypeDef lsm6dso_config (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout)
HAL_StatusTypeDef lsm6dso_readAccel (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout, int16_t *x, int16_t *y, int16_t *z)
HAL_StatusTypeDef lsm6dso_readGyro (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout, int16_t *x, int16_t *y, int16_t *z)
HAL_StatusTypeDef lsm6dso_readTemp (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout, int16_t *temp)
uint8_t lsm6dso_readStatus (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout)
uint8_t lsm6dso_whoIam (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout)
HAL_StatusTypeDef lsm6dso_resetSoftware (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout)
HAL_StatusTypeDef lsm6dso_resetMemory (I2C_HandleTypeDef *hi2c, uint16_t DevAddress, uint32_t Timeout)
Detailed Description
: LSM6DSO IMU library.
Author
Rubén Torres Bermúdez ruben.nosp@m.torr.nosp@m.esber.nosp@m.mude.nosp@m.z@gma.nosp@m.il.c.nosp@m.om
Attention
Created on: 25.06.2023
Description: This library is used to control a LSM6DSO IMU.
Copyright (C) 2023 Rubén Torres Bermúdez
Definition in file lsm6dso.c.
Macro Definition Documentation
INC_LSM6DSO_C_
#define INC_LSM6DSO_C_
Definition at line 20 of file lsm6dso.c.
Function Documentation
lsm6dso_config()
HAL_StatusTypeDef lsm6dso_config (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout)
Common configuration for LSM6DSO
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
Returns
HAL status
Definition at line 32 of file lsm6dso.c.
Referenced by aocs_config_imu().
lsm6dso_readAccel()
HAL_StatusTypeDef lsm6dso_readAccel (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout, int16_t * x, int16_t * y, int16_t * z)
Read linear acceleration sensor
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
x Pointer to x-axis value
y Pointer to y-axis value
z Pointer to z-axis value
Returns
HAL status
Definition at line 144 of file lsm6dso.c.
Referenced by aocs_get_accel(), and aocs_get_imu().
lsm6dso_readGyro()
HAL_StatusTypeDef lsm6dso_readGyro (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout, int16_t * x, int16_t * y, int16_t * z)
Read angular acceleration sensor
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
x Pointer to x-axis value
y Pointer to y-axis value
z Pointer to z-axis value
Returns
HAL status
Definition at line 171 of file lsm6dso.c.
Referenced by aocs_get_gyro(), and aocs_get_imu().
lsm6dso_readStatus()
uint8_t lsm6dso_readStatus (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout)
Read status register
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
Returns
HAL status
Definition at line 216 of file lsm6dso.c.
Referenced by aocs_get_accel(), aocs_get_gyro(), and aocs_get_imu().
lsm6dso_readTemp()
HAL_StatusTypeDef lsm6dso_readTemp (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout, int16_t * temp)
Read temperature sensor
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
temp Pointer to temperature
Returns
HAL status
Definition at line 196 of file lsm6dso.c.
Referenced by aocs_get_imu().
lsm6dso_resetMemory()
HAL_StatusTypeDef lsm6dso_resetMemory (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout)
Reset memory contents
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
Returns
HAL status
Definition at line 267 of file lsm6dso.c.
lsm6dso_resetSoftware()
HAL_StatusTypeDef lsm6dso_resetSoftware (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout)
Software reset
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
Returns
HAL status
Definition at line 246 of file lsm6dso.c.
lsm6dso_whoIam()
uint8_t lsm6dso_whoIam (I2C_HandleTypeDef * hi2c, uint16_t DevAddress, uint32_t Timeout)
Read WHO I AM register
Parameters
hi2c Pointer to a I2C_HandleTypeDef structure
DevAddress Device address
Timeout Timeout duration
Returns
Device response
Definition at line 232 of file lsm6dso.c.
References hi2c1.
Referenced by aocs_config_imu().