My Project: ms5607.c File Reference
ms5607.c File Reference
: MS5607 altimeter library.
#include "ms5607.h"
Functions
HAL_StatusTypeDef ms5607_reset ()
HAL_StatusTypeDef ms5607_readCalibration (uint16_t *cal)
HAL_StatusTypeDef ms5607_getTemp (uint8_t osr, uint16_t *cal, float *temp)
HAL_StatusTypeDef ms5607_getTempPressure (uint8_t osr, uint16_t *cal, float *temp, float *pressure)
float ms5607_getAltitude (float pressure)
Detailed Description
: MS5607 altimeter library.
Author
Rubén Torres Bermúdez ruben.nosp@m.torr.nosp@m.esber.nosp@m.mude.nosp@m.z@gma.nosp@m.il.c.nosp@m.om
Attention
Created on: 10.09.2023
Description: This library is used to control a MS5607 altimeter.
Copyright (C) 2021 Rubén Torres Bermúdez
Definition in file ms5607.c.
Function Documentation
ms5607_getAltitude()
float ms5607_getAltitude (float pressure)
Convert pressure to altitude
Parameters
pressure Pressure to conversion to altitude
Returns
Altitude conversion
Definition at line 182 of file ms5607.c.
Referenced by aocs_get_altimeter().
ms5607_getTemp()
HAL_StatusTypeDef ms5607_getTemp (uint8_t osr, uint16_t * cal, float * temp)
Perform a conversion and read temperature
Parameters
osr OSR set for ADC
cal Calibration values
temp Pointer to temperature
Returns
HAL status
Definition at line 117 of file ms5607.c.
ms5607_getTempPressure()
HAL_StatusTypeDef ms5607_getTempPressure (uint8_t osr, uint16_t * cal, float * temp, float * pressure)
Perform two conversions and read temperature and pressure
Parameters
osr OSR set for ADC
cal Calibration values
temp Pointer to temperature
pressure Pointer to pressure
Returns
HAL status
Definition at line 143 of file ms5607.c.
Referenced by aocs_get_altimeter().
ms5607_readCalibration()
HAL_StatusTypeDef ms5607_readCalibration (uint16_t * cal)
Read calibration values from PROM
Parameters
cal Pointer to calibration values
Returns
HAL status
Definition at line 96 of file ms5607.c.
Referenced by aocs_config_altimeter().
ms5607_reset()
HAL_StatusTypeDef ms5607_reset ()
Perform a device reset
Returns
HAL status
Definition at line 83 of file ms5607.c.
References hi2c1.
Referenced by aocs_config_altimeter().