My Project: stm32l4xx_hal_msp.c File Reference
stm32l4xx_hal_msp.c File Reference
This file provides code for the MSP Initialization and de-Initialization codes.
#include "main.h"
Functions
void HAL_MspInit (void)
void HAL_CRC_MspInit (CRC_HandleTypeDef *hcrc)
CRC MSP Initialization This function configures the hardware resources used in this example.
void HAL_CRC_MspDeInit (CRC_HandleTypeDef *hcrc)
CRC MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_I2C_MspInit (I2C_HandleTypeDef *hi2c)
I2C MSP Initialization This function configures the hardware resources used in this example.
void HAL_I2C_MspDeInit (I2C_HandleTypeDef *hi2c)
I2C MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_UART_MspInit (UART_HandleTypeDef *huart)
UART MSP Initialization This function configures the hardware resources used in this example.
void HAL_UART_MspDeInit (UART_HandleTypeDef *huart)
UART MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_RTC_MspInit (RTC_HandleTypeDef *hrtc)
RTC MSP Initialization This function configures the hardware resources used in this example.
void HAL_RTC_MspDeInit (RTC_HandleTypeDef *hrtc)
RTC MSP De-Initialization This function freeze the hardware resources used in this example.
void HAL_TIM_Base_MspInit (TIM_HandleTypeDef *htim_base)
TIM_Base MSP Initialization This function configures the hardware resources used in this example.
void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef *htim_base)
TIM_Base MSP De-Initialization This function freeze the hardware resources used in this example.
Variables
DMA_HandleTypeDef hdma_lpuart_tx
DMA_HandleTypeDef hdma_usart1_tx
DMA_HandleTypeDef hdma_usart3_rx
Detailed Description
This file provides code for the MSP Initialization and de-Initialization codes.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file stm32l4xx_hal_msp.c.
Function Documentation
HAL_CRC_MspDeInit()
void HAL_CRC_MspDeInit (CRC_HandleTypeDef * hcrc)
CRC MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
hcrc CRC handle pointer
Return values
None
Definition at line 112 of file stm32l4xx_hal_msp.c.
References hcrc.
HAL_CRC_MspInit()
void HAL_CRC_MspInit (CRC_HandleTypeDef * hcrc)
CRC MSP Initialization This function configures the hardware resources used in this example.
Parameters
hcrc CRC handle pointer
Return values
None
Definition at line 90 of file stm32l4xx_hal_msp.c.
References hcrc.
HAL_I2C_MspDeInit()
void HAL_I2C_MspDeInit (I2C_HandleTypeDef * hi2c)
I2C MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
hi2c I2C handle pointer
Return values
None
I2C1 GPIO Configuration PA9 ---—> I2C1_SCL PA10 ---—> I2C1_SDA
Definition at line 180 of file stm32l4xx_hal_msp.c.
HAL_I2C_MspInit()
void HAL_I2C_MspInit (I2C_HandleTypeDef * hi2c)
I2C MSP Initialization This function configures the hardware resources used in this example.
Parameters
hi2c I2C handle pointer
Return values
None
Initializes the peripherals clock
I2C1 GPIO Configuration PA9 ---—> I2C1_SCL PA10 ---—> I2C1_SDA
Definition at line 134 of file stm32l4xx_hal_msp.c.
References Error_Handler().
HAL_MspInit()
void HAL_MspInit (void)
Initializes the Global MSP.
Definition at line 68 of file stm32l4xx_hal_msp.c.
HAL_RTC_MspDeInit()
void HAL_RTC_MspDeInit (RTC_HandleTypeDef * hrtc)
RTC MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
hrtc RTC handle pointer
Return values
None
Definition at line 502 of file stm32l4xx_hal_msp.c.
References hrtc.
HAL_RTC_MspInit()
void HAL_RTC_MspInit (RTC_HandleTypeDef * hrtc)
RTC MSP Initialization This function configures the hardware resources used in this example.
Parameters
hrtc RTC handle pointer
Return values
None
Initializes the peripherals clock
Definition at line 469 of file stm32l4xx_hal_msp.c.
References Error_Handler(), and hrtc.
HAL_TIM_Base_MspDeInit()
void HAL_TIM_Base_MspDeInit (TIM_HandleTypeDef * htim_base)
TIM_Base MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
htim_base TIM_Base handle pointer
Return values
None
Definition at line 574 of file stm32l4xx_hal_msp.c.
HAL_TIM_Base_MspInit()
void HAL_TIM_Base_MspInit (TIM_HandleTypeDef * htim_base)
TIM_Base MSP Initialization This function configures the hardware resources used in this example.
Parameters
htim_base TIM_Base handle pointer
Return values
None
Definition at line 524 of file stm32l4xx_hal_msp.c.
HAL_UART_MspDeInit()
void HAL_UART_MspDeInit (UART_HandleTypeDef * huart)
UART MSP De-Initialization This function freeze the hardware resources used in this example.
Parameters
huart UART handle pointer
Return values
None
LPUART1 GPIO Configuration PB10 ---—> LPUART1_RX PB11 ---—> LPUART1_TX
USART1 GPIO Configuration PB6 ---—> USART1_TX PB7 ---—> USART1_RX
USART3 GPIO Configuration PC10 ---—> USART3_TX PC11 ---—> USART3_RX
Definition at line 389 of file stm32l4xx_hal_msp.c.
HAL_UART_MspInit()
void HAL_UART_MspInit (UART_HandleTypeDef * huart)
UART MSP Initialization This function configures the hardware resources used in this example.
Parameters
huart UART handle pointer
Return values
None
Initializes the peripherals clock
LPUART1 GPIO Configuration PB10 ---—> LPUART1_RX PB11 ---—> LPUART1_TX
Initializes the peripherals clock
USART1 GPIO Configuration PB6 ---—> USART1_TX PB7 ---—> USART1_RX
Initializes the peripherals clock
USART3 GPIO Configuration PC10 ---—> USART3_TX PC11 ---—> USART3_RX
Definition at line 211 of file stm32l4xx_hal_msp.c.
References Error_Handler(), hdma_lpuart_tx, hdma_usart1_tx, and hdma_usart3_rx.
Variable Documentation
hdma_lpuart_tx
DMA_HandleTypeDef hdma_lpuart_tx
Definition at line 90 of file main.c.
Referenced by HAL_UART_MspInit().
hdma_usart1_tx
DMA_HandleTypeDef hdma_usart1_tx
Definition at line 91 of file main.c.
Referenced by HAL_UART_MspInit().
hdma_usart3_rx
DMA_HandleTypeDef hdma_usart3_rx
Definition at line 92 of file main.c.
Referenced by HAL_UART_MspInit().